name: via
channels:
  - robostack-staging
  - conda-forge
dependencies:
  - python=3.11
  - ros-noetic-kdl-parser
  - cxx-compiler
  - cmake
  - ninja
  - orocos-kdl
  - eigen
  - boost
  - spdlog
  - pybind11
  - numpy
  - click
  - pyzmq
  - pynput
  - pip
  - conda-forge::soem # This package is missing in aarch64
  # To install it on aarch64 (arm64), comment out this package and first create the arx-py311 environment.
  # Directly clone the SOEM repository and install it to the conda environment (ensure $CONDA_PREFIX points to arx-py311):
  # `conda activate arx-py311`
  # `git clone https://github.com/OpenEtherCATsociety/SOEM.git && cd SOEM`
  # `mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .. && make -j && make install`
  - pip:
      - atomics
      - spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz 
      - torch==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - torchaudio==2.7.1+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - accelerate==1.7.0
      - wandb==0.20.1
      - zarr==2.12.0
      - numcodecs==0.12.1
      - huggingface_hub==0.25.1 
      - diffusers==0.18.2
      - open3d
      - numpy-quaternion
      - scikit-image
      - record3d
      - 'vuer[all]==0.0.32-rc29'
      - pytransform3d
      - aiohttp==3.9.5
      - aiohttp_cors==0.7.0
      - aiortc==1.8.0
      - av==11.0.0
      - keyboard
